export const SET_CURRENT_PRICE = 'SET_CURRENT_PRICE'
export const SET_CURRENT_COUNT = 'SET_CURRENT_COUNT'
export const SET_CHANGE_CART = 'SET_CHANGE_CART'
export const SET_CURRENT_CART = 'SET_CURRENT_CART'