import Layout from "@/components/layout";
import { UserProvider } from "@/providers/UserProvider";
import {Provider} from "react-redux"
import { store } from "@/store/store";
import Head from "next/head";
import "@/styles/globals.css"
import {Inter} from "@next/font/google"
import { AnimatePresence, motion } from "framer-motion";
import { useRouter } from "next/router";
const inter = Inter({
  weight:['400'],
  style: ['normal'],
  subsets:['latin']
})
export const metadata = {
  title: 'Leoshop',
  description: 'Generated by create next app'
}

function MyApp({ Component, pageProps }) {
  const router = useRouter()
  return (
    <>
    <Head>
    </Head>
    <UserProvider>
      <Provider store={store}>
          <Layout>
              <div id="root" className={inter.className} key={router.pathname}>
                <AnimatePresence mode="wait">
                  <Component {...pageProps} />
                  {/* <motion.div className="slide-in"
                  initial = {{scaleY: 0}}
                  animate = {{scaleY: 0}}
                  exit={{scaleY: 1}}
                  transition={{duration: 1, ease: [0.22, 1, 0.36, 1]}}>
                  </motion.div>
                  <motion.div className="slide-out"
                  initial = {{scaleY: 1}}
                  animate = {{scaleY: 0}}
                  exit={{scaleY: 0}}
                  transition={{duration: 1, ease: [0.22, 1, 0.36, 1]}}>
                  </motion.div> */}
                </AnimatePresence>
              </div>
          </Layout>
      </Provider>
    </UserProvider>
    </>
  );
}

export default MyApp;
