import Layout from "@/components/layout";
import { UserProvider } from "@/providers/UserProvider";
import {Provider} from "react-redux"
import { store } from "@/store/store";
import Head from "next/head";
import "@/styles/globals.css"
import {Inter} from "@next/font/google"
import { useRouter } from "next/router";
const inter = Inter({
  weight:['400'],
  style: ['normal'],
  subsets:['latin']
})
export const metadata = {
  title: 'Leoshop',
  description: 'Generated by create next app'
}

function MyApp({ Component, pageProps }) {
  const router = useRouter()
  return (
    <>
    <Head>
    </Head>
    <UserProvider>
      <Provider store={store}>
          <Layout>
              <div id="root" className={inter.className} key={router.pathname}>
                  <Component {...pageProps} />
              </div>
          </Layout>
      </Provider>
    </UserProvider>
    </>
  );
}

export default MyApp;
